---
title: A instrução 'Throw' não pode omitir o operando fora de uma instrução 'Catch' ou dentro de uma instrução 'Finally'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: c4ab115b01e78c245cbd9f564b50573d6e30c5e7
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 06/04/2020
ms.locfileid: "84414927"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a>A instrução 'Throw' não pode omitir o operando fora de uma instrução 'Catch' ou dentro de uma instrução 'Finally'
`Throw`as instruções fora da `Catch` instrução devem fornecer o nome de um objeto de exceção.  
  
 **ID do erro:** BC30666  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
1. Especifique o nome de um objeto de exceção derivado de `System.Exception` .  
  
2. Reestruture seu código para que a `Throw` instrução esteja dentro de um `Catch` bloco.  
  
## <a name="see-also"></a>Confira também

- [Instrução Throw](../language-reference/statements/throw-statement.md)
- [Instrução Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [Tratando e gerando exceções no .NET](../../standard/exceptions/index.md)
