---
title: Bloco 'Catch' nunca alcançado; <exception> manipulado acima na mesma instrução 'Try'
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: 987a509b4b099a0a1f728f55dfb2b35a8770af3f
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 06/04/2020
ms.locfileid: "84395474"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a>Bloco 'Catch' nunca alcançado; \<exception> manipulado acima na mesma instrução 'Try'
`Catch`Não é possível acessar um bloco no código porque ele é tratado em um `Try` bloco anterior.  
  
Por padrão, esta mensagem é um aviso. Para obter mais informações sobre como ocultar avisos ou tratar avisos como erros, consulte [Configurando avisos no Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).
  
 **ID do erro:** BC42031  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
- Remova a instrução redundante.  
  
## <a name="see-also"></a>Confira também

- [Como usar o bloco try/catch para capturar exceções](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [Usando manipuladores de exceção filtrados por usuário](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [Instrução Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
